sources:
  - ./RX_Demo # you can provide either single path or several paths using `-`
templates:
  - ./Templates/Available # as well as for templates
output:
  ./RX_Demo/CodeGenerated/AutoCodable.swift
